### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by Ambrevar** [thierryvolpiatto/helm-gentoo#1]
Are you still maintaining this?

I had a look at the code and it looks awesome!

I can't get it to work, though.  The Helm buffer is empty.
I did not investigate much but the least I know is that `helm-cache-world` and `helm-cache-gentoo` are properly initialized.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Are you still maintaining this?

No as I don't use anymore Gentoo.

> I had a look at the code and it looks awesome!

IIRC it was really helpful to manage gentoo packages, use flags etc...

> I can't get it to work, though. The Helm buffer is empty.  I did not
> investigate much but the least I know is that helm-cache-world and
> helm-cache-gentoo are properly initialized.

Probably the code needs to be updated, it is old and many things have
changed in Helm.

If you want I can give you write access to it to fix/maintain it.

--
Thierry

**Comment by Ambrevar** [comment]
With pleasure!

Once polished, would you mind if I publish it on Melpa?

Any pointer to which parts need updating? I am not familiar with Helm of year 2014 :)

**Comment by thierryvolpiatto** [comment]
I moved this to emacs-helm/helm-gentoo and gave you write access.
Of course you can put it on Melpa when you feel it is working fine.
Thanks.

-- 
Thierry

**Comment by Ambrevar** [comment]
Work in progress: https://github.com/melpa/melpa/pull/5195.
Thank you for this.
